#encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#application
spring.application.name=Docktor

#Port
server.port=8080

#DataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#AWS DB
spring.config.import=optional:classpath:application-secret.properties
spring.datasource.url=jdbc:mysql://docktor-rdb.ctmawgggo2cr.ap-northeast-2.rds.amazonaws.com:3306/docktor?serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=admin

#MyBatis
mybatis.type-aliases-package=com.ssafy.docktor.**.dto
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# File Upload Size Limit (100MB)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#JWT
jwt.secret=your-256-bit-secret-key-change-this-in-production-environment-for-security
jwt.expiration=7000000

#Prometheus
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=Docktor
spring.autoconfigure.exclude=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
robot.flask.url=http://192.168.30.163:5000/move
# robot.flask.url=http://192.168.0.9:5000/move


# Redis ??
# spring.data.redis.host=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.refresh-token-expiration = 500000

# MQTT Configuration
mqtt.broker.url=tcp://i14e201.p.ssafy.io:1883
mqtt.client.id=docktor-spring-server
mqtt.topic.robot-move=robot/orin_01/move

# MQTT ?? ?? (??? ??)
mqtt.connection.timeout=10
mqtt.keep-alive=20
mqtt.max-inflight=100
mqtt.clean-session=true
# ?? ????? ? ?? false? ??? ??? Client ID ?? ??
mqtt.use-unique-id=true

# API ??
api.callback.url=https://i14e201.p.ssafy.io/api/inspect/callback

# SSAFY GMS API ??
spring.ai.openai.base-url=https://gms.ssafy.io/gmsapi/api.openai.com
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7

# S3 ??
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=docktor-bucket
cloud.aws.stack.auto=false